name: Docker Build and Push

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Frontend
      run: |
        # Build frontend Docker image using production Dockerfile
        docker build -f ./frontend/Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest ./frontend
        # Push to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
        
    - name: Build and Push Backend
      run: |
        # Build backend Docker image using production Dockerfile
        docker build -f ./backend/Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest ./backend
        # Push to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
        
    # Optional: DB image if not using Render's managed DB
    - name: Build and Push DB
      run: |
        # Check for database Dockerfiles
        if [ -f "./database/Dockerfile.prod" ]; then
          docker build -f ./database/Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-db:latest ./database
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-db:latest
        elif [ -f "./database/Dockerfile" ]; then
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-db:latest ./database
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-db:latest
        else
          echo "No database Dockerfile found, skipping DB image build"
        fi